
one_d="[Dialogue]: Tim: Hi, what's up?\nKim: Bad mood tbh, I was going to do lots of stuff but ended up procrastinating\nTim: What did you plan on doing?\nKim: Oh you know, uni stuff and unfucking my room\nKim: Maybe tomorrow I'll move my ass and do everything\nKim: We were going to defrost a fridge so instead of shopping I'll eat some defrosted veggies\nTim: For doing stuff I recommend Pomodoro technique where u use breaks for doing chores\nTim: It really helps\nKim: thanks, maybe I'll do that\nTim: I also like using post-its in kaban style\n\n"
one_d_summary="Kim may try the pomodoro technique recommended by Tim to get more stuff done.\n\n"
sam_two_d="[Dialogue]: Anita: I'm at the station in Bologna\nJenny: No problems so far?\nAnita: no, everything's going smoothly\nTomy: good!\n\n"
sam_two_d_summary="Anita is at Bologna station.\n\n"

sam_three_d="[Dialogue]: Elisa: Who wants to come for drinks tonight at Mombasa?\nAlice: me!\nSadie: I'm in as well\nCarol: may I bring some people?\nElisa: sure, the more the better!\nCarol: amazing\nArthur: count me in! I'll come with Alice of course\nLiam: me too!\nKai: I will join you but after my courses, around 8\nElisa: No problem, we'll be there till midnight at least\nTom: i may come over :)\nElisa: Anybody else? I'd like to book the corner table\nTom: the big one?\nElisa: exactly\nJohn: So count me in as well\nElisa: Perfect, the table is for 15 people so we should manage! See you there\n\n"
sam_three_d_summary="Elisa, Sadie, Carol, Liam, Tom and John want to go for drinks tonight at Mombasa. Arthur will come with Alice. Kai will join them around 8. Elisa will book the big corner table for 15 people.\n\n"
sam_four_d="[Dialogue]: Isabella: fuck my life, I'm so not able to get up to work today\nIsabella: I need to call in sick :(\nOscar: haha, well you certainly had a good time at the Christmas party yesterday XD\nIsabella: shut up, you're a traitor\nIsabella: I told you to guard my glass\nIsabella: and my sobriety. You clearly failed!\nOscar: but you were having such fun, I didn't have a heart to stop it\nOscar: <file_photo>\nOscar: <file_photo>\nIsabella: you're so dead! Is that Jimmy from marketing department?\nOscar: yes indeed, it's him :D\nIsabella: I am a fallen woman, I cannot get back to the office now\nIsabella: <file_gif>\nOscar: oh come on, almost everybody was drunk\nOscar: so they won't remember a thing :D\nIsabella: I assure you, they tend to remember such things…\nOscar: <file_gif>\n\n"
sam_four_d_summary="Isabella feels bad after the Christmas party. She got drunk. She is ashamed to go back to work.\n\n"

sam_five_d="[Dialogue]: Maria: Guys, don't bring anything, I've cooked so much\nAndrew: We will bring some wine we bought in Italy last year\nMartha: Especially for a night like this\nMaria: How nice of you!! thanks\n\n"
sam_five_d_summary="Maria has cooked a lot of food. Andrew will bring some Italian wine.\n\n"



dialogsum_one_d="[Dialogue]: #Person1#: Hi, Mr. Smith. I'm Doctor Hawkins. Why are you here today?\n#Person2#: I found it would be a good idea to get a check-up.\n#Person1#: Yes, well, you haven't had one for 5 years. You should have one every year.\n#Person2#: I know. I figure as long as there is nothing wrong, why go see the doctor?\n#Person1#: Well, the best way to avoid serious illnesses is to find out about them early. So try to come at least once a year for your own good.\n#Person2#: Ok.\n#Person1#: Let me see here. Your eyes and ears look fine. Take a deep breath, please. Do you smoke, Mr. Smith?\n#Person2#: Yes.\n\n"
dialogsum_one_d_summary="Mr. Smith's getting a check-up, and Doctor Hawkins advises him to have one every year. Hawkins'll give some information about their classes and medications to help Mr. Smith quit smoking.\n\n"
two_d="[Dialogue]: #Person1#: Please make yourselves at home. Let me take your coats. Dinner is almost ready. I hope you brought your appetite \n#Person2#: Your house is lovely, Armand! Very interesting decor.. very Gothic.\n#Person3#: I think it's amazing! You have such good taste, Armand. I'm thinking of re-decorating my house. maybe you could give me a few pointers? \n#Person1#: It would be my pleasure. Please have a seat. Can I offer you a glass of wine? \n#Person3#: We would love some! \n#Person1#: Here you are. A very special merlot brought directly from my home country. It has a unique ingredient which gives it a pleasant aroma and superior flavor \n#Person3#: Mmm.  it's delicious! \n#Person2#: It's a bit bitter for my taste. . . almost tastes like. . . like. . . \n#Person3#: Ellen! Are you okay? \n#Person1#: Did she pass out? \n#Person3#: Yeah.\n\n"
two_d_summary="Ellen and #Person3# visit Armand's house, and they have dinner together. The glass of wine provided by Armand is a bit bitter for Ellen, and she passes out.\n\n"
three_d="[Dialogue]: #Person1#: Here we come.\n#Person2#: Thank you. What's the fare?\n#Person1#: $ 10.\n#Person2#: How can it be?\n#Person1#: Well, the rate is two dollars for the first two kilometers and twenty cents for each additional two hundred meters.\n#Person2#: I see. Thanks for your drive.\n\n"
three_d_summary="#Person1# tells #Person2# the fare of taking a taxi.\n\n"

four_d="[Dialogue]: #Person1#: Suppose the company offer you a pay raise of 50%, would you be so determined to leave and look for a job as well?\n#Person2#: Yes, I've set my mind down on it. I'd like to find a job with full scope to show my ability.\n\n"
four_d_summary="#Person1# refuses a pay raise and determines to leave the company.\n\n"

five_d="[Dialogue]: #Person1#: Does it look like a good fit?\n#Person2#: It's definitely your size.\n#Person1#: Yes, it is very nice. I'll take it.\n#Person2#: How do you prefer to pay?\n#Person1#: Let me use my credit card.\n#Person2#: Now, if you'll just sign here.\n#Person1#: No problem.\n#Person2#: I hope you enjoy your purchase. Good-bye.\n\n"
five_d_summary="#Person1# buys some nice clothes by credit card with #Person2#'s assistance.\n\n"